# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

r:
 - devel

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openmpi-common openmpi-bin libopenmpi-dev

r_packages:
  - testthat
  - extraDistr
  - copula

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

script:
  - make install
  - make check
  - make test
